sudo: false
language: python
python:
  - "3.7.6"
install:
  - pip install flake8>=3.7.8
  - pip install -r requirements.txt
script:
  - flake8 --ignore=F401
  - python keras_layernorm_rnn/layernorm_simplernn_test.py
cache: pip
